# -*- coding: utf-8 -*-
"""
可见水印 OCR 检测模块
对图像四角进行多尺度裁剪 + EasyOCR 文字识别，判断是否包含 AI 平台水印/签名
检测到水印 → 直接判定为 AI 生成图片（短路）

依赖: easyocr, opencv-python, numpy
"""

import os
import cv2
import numpy as np
import re
from difflib import SequenceMatcher

# ── 全局 OCR 实例（懒加载，避免每次重新初始化） ──
_ocr_reader = None


def _get_ocr():
    """获取 EasyOCR Reader 实例（懒加载）"""
    global _ocr_reader
    if _ocr_reader is None:
        import easyocr
        _ocr_reader = easyocr.Reader(['ch_sim', 'en'], gpu=False)
    return _ocr_reader


def _imread_unicode(path):
    """
    支持 Unicode/中文路径的 imread
    OpenCV 的 cv2.imread 在 Windows 上不支持中文路径，需要用 imdecode 绕行
    """
    try:
        with open(path, 'rb') as f:
            raw = np.frombuffer(f.read(), dtype=np.uint8)
        img = cv2.imdecode(raw, cv2.IMREAD_COLOR)
        return img
    except Exception:
        return None


# ═══════════════════════════════════════════════════════════════
# AI 平台水印关键词库
# ═══════════════════════════════════════════════════════════════
KEYWORDS_BY_PLATFORM = {
    # 国内平台
    "豆包": ["doubao", "豆包", "字节跳动"],
    "即梦": ["即梦", "jimeng", "jimeng ai"],
    "通义千问/万相": ["通义千问", "通义万相", "通义", "tongyi", "qwen", "千问", "万相"],
    "文心一格": ["文心一格", "文心", "yige", "ernie-vilg", "文心一言"],
    "讯飞星火": ["讯飞星火", "星火", "spark"],
    "智谱清影/清言": ["智谱", "清影", "cogview", "清言", "chatglm", "zhipu"],
    "混元": ["混元", "hunyuan", "腾讯混元"],
    "可灵": ["可灵", "kling", "kuaishou"],
    "奇域": ["奇域", "qiyu"],
    "堆友": ["堆友"],
    "LiblibAI": ["liblib", "liblibai"],
    "吐司": ["吐司", "tusiart"],

    # 国外平台
    "DALL·E": ["dall·e", "dall-e", "dalle", "openai"],
    "Midjourney": ["midjourney", "mj"],
    "Stable Diffusion": ["stable diffusion", "stability ai"],
    "Bing Image Creator": ["bing image", "microsoft designer", "bing creator"],
    "Adobe Firefly": ["firefly", "adobe firefly"],
    "NovelAI": ["novelai", "novel ai"],
    "Ideogram": ["ideogram"],
    "Flux": ["flux", "flux.1", "flux pro"],
    "Leonardo": ["leonardo", "leonardo ai"],
    "SeaArt": ["seaart", "sea art"],
    "Playground": ["playground", "playground ai"],

    # 通用 AI 生成标识
    "AI通用标识": ["ai生成", "aigc", "ai generated", "generated by ai",
                   "created with ai", "ai image", "ai创作"],
}


def _normalize(text):
    """标准化文本：去空白、小写"""
    return re.sub(r'\s+', '', text).lower()


def _fuzzy_match(text, keyword, threshold=0.85):
    """
    模糊匹配：忽略大小写 + 编辑距离容忍
    - 完全包含 → 直接 True
    - 单字关键词 → 子串包含检测
    - 否则用 SequenceMatcher 计算相似度
    """
    t = _normalize(text)
    k = _normalize(keyword)

    # 子串包含检测
    if k in t or t in k:
        return True

    # 单字关键词：放宽要求，只要原文中出现即可（用于 OCR 碎片匹配）
    if len(k) == 1 and len(t) >= 1:
        return k in t

    # 短词 (<3) 要求 100% 匹配
    if len(k) <= 3:
        return k == t

    # 编辑距离相似度
    ratio = SequenceMatcher(None, t, k).ratio()
    # 长度差异惩罚
    len_penalty = min(len(t), len(k)) / max(len(t), len(k))
    adjusted = ratio * len_penalty

    return adjusted >= threshold


# AI 生成类关键词后缀 —— 用于确认碎片匹配确实来自水印
_AI_SUFFIX_WORDS = [
    '生成', '创作', '创造', '生图', '生文', '绘', '画', '制', '作',
    'ai', 'aigc', 'pro', 'create', 'generate', 'made',
    '成', '图', '像',  # OCR 碎片常见截断
]


def _has_ai_suffix(text):
    """检查 OCR 文本中是否包含 AI 生成类后缀词"""
    t = _normalize(text)
    return any(s in t for s in _AI_SUFFIX_WORDS)


def _match_keywords(ocr_texts, keywords_dict=None):
    """
    在 OCR 结果中匹配关键词，支持全文匹配和碎片匹配两级策略

    参数:
        ocr_texts:     OCR 识别到的文字列表
        keywords_dict: 关键词字典 {平台名: [关键词列表]}，默认使用 KEYWORDS_BY_PLATFORM

    返回:
        list[dict]: 匹配到的结果 [{platform, keyword, text, position}]
    """
    if keywords_dict is None:
        keywords_dict = KEYWORDS_BY_PLATFORM

    matches = []

    for text in ocr_texts:
        if not text or len(text.strip()) < 2:
            continue
        t_norm = _normalize(text)

        for platform, keywords in keywords_dict.items():
            # 第一层：完整关键词匹配
            for kw in keywords:
                if _fuzzy_match(text, kw):
                    matches.append({
                        'platform': platform,
                        'keyword': kw,
                        'detected_text': text,
                        'match_type': 'full',
                    })
                    break  # 同一平台只记一次 full match

            # 第二层：碎片匹配 —— 单字命中 + AI 后缀确认
            # 适用于 OCR 误读场景，如"豆包"被读成"豆A"
            if not any(m['platform'] == platform for m in matches):
                for kw in keywords:
                    k_norm = _normalize(kw)
                    # 只对中文多字关键词做碎片匹配（英文不适用）
                    if len(k_norm) >= 2 and any('\u4e00' <= c <= '\u9fff' for c in k_norm):
                        # 逐个字检查
                        chars_found = []
                        for ch in k_norm:
                            if ch in t_norm:
                                chars_found.append(ch)
                        # 如果关键字的字符在 OCR 文本中出现了 ≥ 一半，且包含 AI 后缀 → 确认水印
                        if len(chars_found) >= len(k_norm) // 2 + 1 and _has_ai_suffix(text):
                            matches.append({
                                'platform': platform,
                                'keyword': kw,
                                'detected_text': text,
                                'match_type': 'fragment',
                                'matched_chars': chars_found,
                            })
                            break

    return matches


def _crop_four_corners(img_bgr, ratios=(0.10, 0.16, 0.24, 0.30)):
    """
    对图像四角进行多尺度裁剪

    参数:
        img_bgr: OpenCV BGR 图像（numpy 数组）
        ratios:  裁剪比例列表（相对于图像宽高的比例）

    返回:
        list[dict]: [{ 'corner': 'top_left'/'top_right'/'bottom_left'/'bottom_right',
                       'ratio': 0.15,
                       'region': numpy_array }]
    """
    h, w = img_bgr.shape[:2]
    patches = []

    corners = {
        'top_left':     (0, 0, lambda cw, ch: (0, 0, cw, ch)),
        'top_right':    (1, 0, lambda cw, ch: (w - cw, 0, w, ch)),
        'bottom_left':  (0, 1, lambda cw, ch: (0, h - ch, cw, h)),
        'bottom_right': (1, 1, lambda cw, ch: (w - cw, h - ch, w, h)),
    }

    for corner_name, (_, _, get_roi) in corners.items():
        for ratio in ratios:
            cw = int(w * ratio)
            ch = int(h * ratio)
            x1, y1, x2, y2 = get_roi(cw, ch)
            region = img_bgr[y1:y2, x1:x2]
            patches.append({
                'corner': corner_name,
                'ratio': ratio,
                'region': region,
                'bbox': (x1, y1, x2, y2),
            })

    return patches


def _preprocess_for_ocr(img_bgr):
    """
    OCR 预处理管线：
    灰度化 → CLAHE 对比度增强 → 轻度锐化

    EasyOCR 是基于深度学习的，需要自然图像输入，不能用二值化！
    返回: 增强后的灰度图（单通道 uint8）
    """
    # 灰度化
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

    # CLAHE 对比度增强
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(gray)

    return enhanced


def _preprocess_variants(img_bgr):
    """
    生成多个预处理变体，逐个尝试以提高 OCR 命中率

    返回: list of (name, image) 元组
    """
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(gray)

    variants = [
        ('原图BGR', img_bgr),
        ('灰度CLAHE', enhanced),
    ]

    # 反转灰度（白色文字在深色背景上 → 黑色文字白色背景）
    inverted = cv2.bitwise_not(gray)
    inverted_enhanced = clahe.apply(inverted)
    variants.append(('灰度反转+CLAHE', inverted_enhanced))

    # 2倍放大 + CLAHE（小文字更容易识别）
    h, w = img_bgr.shape[:2]
    if w < 300 or h < 300:
        upscaled = cv2.resize(img_bgr, (w * 2, h * 2), interpolation=cv2.INTER_CUBIC)
        variants.append(('2倍放大+CLAHE', _preprocess_for_ocr(upscaled)))

    return variants


def _ocr_extract_text(img_bgr):
    """
    对单张图像（或图像区域）执行 OCR，返回识别到的文字列表

    参数:
        img_bgr: OpenCV BGR 图像

    返回:
        list[str]: 识别到的所有文字行
    """
    reader = _get_ocr()
    try:
        results = reader.readtext(img_bgr)
        texts = [item[1] for item in results if item[2] > 0.2]  # item = (bbox, text, confidence)
        return texts
    except Exception:
        return []


def _detect_dalle2_squares(img_bgr):
    """
    检测 DALL·E 2 五色方块水印（右下角区域）
    DALL·E 2 会在图像右下角放置黄/青/绿/红/蓝五种颜色的方块

    返回:
        dict | None: 检测到则返回详情，否则返回 None
    """
    h, w = img_bgr.shape[:2]

    # 仅检查右下角区域 (20%)
    roi = img_bgr[int(h * 0.8):, int(w * 0.8):]
    if roi.size == 0:
        return None

    # 转换到 HSV 色彩空间
    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)

    # DALL·E 2 五种颜色在 HSV 空间的饱和像素统计
    color_ranges = {
        'yellow':  (np.array([20,  120, 120]), np.array([35,  255, 255])),
        'cyan':    (np.array([80,  120, 120]), np.array([100, 255, 255])),
        'green':   (np.array([40,  120, 120]), np.array([75,  255, 255])),
        'red':     (np.array([0,   120, 120]), np.array([10,  255, 255])),
        'blue':    (np.array([100, 120, 120]), np.array([130, 255, 255])),
    }

    color_counts = {}
    total_pixels = roi.shape[0] * roi.shape[1]

    for color_name, (lower, upper) in color_ranges.items():
        mask = cv2.inRange(hsv, lower, upper)
        count = cv2.countNonZero(mask)
        ratio = count / total_pixels if total_pixels > 0 else 0
        color_counts[color_name] = {'count': count, 'ratio': ratio}

    # 判定：至少三种颜色的占比超过 0.5%
    high_saturation_colors = sum(1 for v in color_counts.values() if v['ratio'] > 0.005)

    if high_saturation_colors >= 3:
        return {
            'detected': True,
            'method': 'DALL·E 2 五色方块签名',
            'color_counts': {k: round(v['ratio'], 4) for k, v in color_counts.items()},
            'high_saturation_colors': high_saturation_colors,
        }

    return None


def detect_visible_watermark_fast(image_path):
    """Low-latency local watermark screen for the online review pipeline.

    It intentionally performs one enhanced OCR pass on each corner (four
    passes total) rather than the full detector's multi-scale 48-pass search.
    Only unambiguous platform/AI-generation phrases are reported as positives;
    every miss or weak clue proceeds to cloud review instead of being treated as
    evidence that no watermark exists.
    """
    img = _imread_unicode(image_path)
    empty = {
        'detected': False, 'source': None, 'confidence': 0.0,
        'position': None, 'detected_text': None, 'all_matches': [],
        'all_texts': [], 'method': 'local_ocr_fast', 'review_needed': True,
    }
    if img is None:
        return {**empty, 'detail': '本地 OCR 快筛无法读取图片'}

    dalle2_result = _detect_dalle2_squares(img)
    if dalle2_result:
        return {
            **empty, 'detected': True, 'source': 'DALL·E 2', 'confidence': 0.90,
            'position': 'bottom_right', 'detected_text': '五色方块签名',
            'all_matches': [{'platform': 'DALL·E 2', 'keyword': 'color_squares',
                             'detected_text': '五色方块签名', 'corner': 'bottom_right'}],
            'detail': '本地快筛在右下角检测到 DALL·E 2 五色方块签名',
            'method': 'local_dalle2_signature', 'review_needed': False,
        }

    all_texts, candidates = [], []
    for patch in _crop_four_corners(img, ratios=(0.20,)):
        # One CLAHE pass is sufficient for the inexpensive high-confidence
        # screen.  The exhaustive detector remains available for offline use.
        texts = _ocr_extract_text(_preprocess_for_ocr(patch['region']))
        unique_texts = list(dict.fromkeys(text.strip() for text in texts if text and text.strip()))
        all_texts.extend(unique_texts)
        for match in _match_keywords(unique_texts):
            normalized = _normalize(match['detected_text'])
            keyword = _normalize(match['keyword'])
            if match['platform'] == 'AI通用标识':
                # Bare "AI" is common in normal UI copy and is not enough to
                # shortcut a detection result.
                phrases = ('aigc', 'ai生成', 'ai创作', 'aigenerated', 'generatedbyai', 'createdwithai')
                if not any(phrase in normalized for phrase in phrases):
                    continue
                confidence = 0.86
            elif match.get('match_type') == 'full' and len(keyword) >= 4:
                confidence = 0.90
            else:
                continue
            candidates.append({**match, 'corner': patch['corner'], 'confidence': confidence})

    if candidates:
        best = max(candidates, key=lambda item: item['confidence'])
        return {
            **empty, 'detected': True, 'source': best['platform'],
            'confidence': best['confidence'], 'position': best['corner'],
            'detected_text': best['detected_text'], 'all_matches': candidates,
            'all_texts': all_texts[:12],
            'detail': f"本地 OCR 快筛在{best['corner']}检测到「{best['platform']}」水印线索",
            'review_needed': False,
        }

    return {**empty, 'detail': '本地 OCR 快筛未发现高置信 AI 平台水印'}


def detect_visible_watermark(image_path):
    """
    可见水印检测统一入口

    流程:
        1. 四角多尺度裁剪（10%/16%/24%/30% × 4角 = 16张子图）
        2. 每张子图多种预处理（原图BGR + 灰度CLAHE + 灰度反转CLAHE）
        3. EasyOCR 提取文字
        4. 关键词模糊匹配
        5. DALL·E 2 五色方块检测（兜底）

    参数:
        image_path: str 图像文件路径

    返回:
        dict: {
            'detected': bool,          # 是否检测到水印
            'source': str | None,      # 来源平台名称
            'confidence': float,        # 综合置信度 0~1
            'position': str | None,    # 水印位置（corner）
            'detected_text': str | None,  # 匹配到的原始文本
            'detail': str,             # 详细说明
            'all_matches': list,       # 所有匹配结果
            'method': str,             # 检测方法 (ocr / dalle2_color)
        }
    """
    img = _imread_unicode(image_path)
    if img is None:
        return {
            'detected': False,
            'source': None,
            'confidence': 0.0,
            'position': None,
            'detected_text': None,
            'detail': '无法读取图片文件（路径可能包含中文）',
            'all_matches': [],
            'all_texts': [],
            'method': 'ocr',
        }

    all_ocr_texts = []
    all_matches = []
    best_match = None
    best_confidence = 0.0

    # ── 1. 四角多尺度 OCR ──
    patches = _crop_four_corners(img)

    for patch in patches:
        # 对该角区域尝试多种预处理变体
        variants = _preprocess_variants(patch['region'])

        all_patch_texts = []
        for variant_name, variant_img in variants:
            texts = _ocr_extract_text(variant_img)
            if texts:
                all_patch_texts.extend(texts)

        if not all_patch_texts:
            continue

        # 去重
        seen = set()
        unique_texts = []
        for t in all_patch_texts:
            t_norm = _normalize(t)
            if t_norm not in seen and len(t.strip()) >= 2:
                seen.add(t_norm)
                unique_texts.append(t)
        all_patch_texts = unique_texts

        # 给每个结果标注位置信息
        for t in all_patch_texts:
            all_ocr_texts.append({
                'text': t,
                'corner': patch['corner'],
                'ratio': patch['ratio'],
            })

        # 关键词匹配
        matches = _match_keywords(all_patch_texts)
        for m in matches:
            m['corner'] = patch['corner']
            m['ratio'] = patch['ratio']
            all_matches.append(m)

            # 优先选择 text 更长的匹配（匹配更精准）
            # 碎片匹配置信度较低（OCR 可能误读）
            match_len = len(m['detected_text'])
            confidence = min(1.0, match_len / 20.0)  # 20 字符以上视为完全匹配
            if m.get('match_type') == 'fragment':
                confidence = confidence * 0.75  # 碎片匹配打折

            if confidence > best_confidence:
                best_confidence = confidence
                best_match = m

    # ── 2. DALL·E 2 五色方块检测 ──
    dalle2_result = _detect_dalle2_squares(img)

    if dalle2_result:
        all_matches.append({
            'platform': 'DALL·E 2',
            'keyword': 'color_squares',
            'detected_text': '五色方块签名',
            'corner': 'bottom_right',
            'ratio': 0.20,
        })
        if best_match is None or best_confidence < 0.7:
            best_match = {
                'platform': 'DALL·E 2',
                'keyword': 'color_squares',
                'detected_text': '五色方块签名',
                'corner': 'bottom_right',
                'ratio': 0.20,
            }
            best_confidence = 0.85

    # ── 3. 组装结果 ──
    if best_match:
        return {
            'detected': True,
            'source': best_match['platform'],
            'confidence': best_confidence,
            'position': best_match.get('corner', None),
            'detected_text': best_match['detected_text'],
            'detail': f"在图像{best_match.get('corner', '未知位置')}检测到「{best_match['platform']}」水印/签名",
            'all_matches': all_matches,
            'all_texts': [t['text'] for t in all_ocr_texts[:10]],  # 最多保留10条 OCR 结果
            'method': 'dalle2_color' if dalle2_result and best_match['keyword'] == 'color_squares' else 'ocr',
        }
    else:
        return {
            'detected': False,
            'source': None,
            'confidence': 0.0,
            'position': None,
            'detected_text': None,
            'detail': '未检测到已知 AI 平台水印',
            'all_matches': [],
            'all_texts': [t['text'] for t in all_ocr_texts[:10]],
            'method': 'ocr',
        }


# ── 便捷函数：纯内存检测（避免磁盘 IO）──
def detect_visible_watermark_from_array(img_array):
    """
    与 detect_visible_watermark 相同，但直接从 numpy 数组检测

    参数:
        img_array: numpy 数组 (H, W, 3) BGR 格式

    返回: 同 detect_visible_watermark
    """
    if img_array is None or img_array.size == 0:
        return {
            'detected': False,
            'source': None,
            'confidence': 0.0,
            'position': None,
            'detected_text': None,
            'detail': '图像数据为空',
            'all_matches': [],
            'all_texts': [],
            'method': 'ocr',
        }

    img = img_array
    all_ocr_texts = []
    all_matches = []
    best_match = None
    best_confidence = 0.0

    # ── 四角多尺度 OCR ──
    patches = _crop_four_corners(img)

    for patch in patches:
        # 对该角区域尝试多种预处理变体
        variants = _preprocess_variants(patch['region'])

        all_patch_texts = []
        for variant_name, variant_img in variants:
            texts = _ocr_extract_text(variant_img)
            if texts:
                all_patch_texts.extend(texts)

        if not all_patch_texts:
            continue

        # 去重
        seen = set()
        unique_texts = []
        for t in all_patch_texts:
            t_norm = _normalize(t)
            if t_norm not in seen and len(t.strip()) >= 2:
                seen.add(t_norm)
                unique_texts.append(t)
        all_patch_texts = unique_texts

        for t in all_patch_texts:
            all_ocr_texts.append({
                'text': t,
                'corner': patch['corner'],
                'ratio': patch['ratio'],
            })

        matches = _match_keywords(all_patch_texts)
        for m in matches:
            m['corner'] = patch['corner']
            m['ratio'] = patch['ratio']
            all_matches.append(m)

            match_len = len(m['detected_text'])
            confidence = min(1.0, match_len / 20.0)
            if confidence > best_confidence:
                best_confidence = confidence
                best_match = m

    # ── DALL·E 2 五色方块 ──
    dalle2_result = _detect_dalle2_squares(img)
    if dalle2_result:
        all_matches.append({
            'platform': 'DALL·E 2',
            'keyword': 'color_squares',
            'detected_text': '五色方块签名',
            'corner': 'bottom_right',
            'ratio': 0.20,
        })
        if best_match is None or best_confidence < 0.7:
            best_match = {
                'platform': 'DALL·E 2',
                'keyword': 'color_squares',
                'detected_text': '五色方块签名',
                'corner': 'bottom_right',
                'ratio': 0.20,
            }
            best_confidence = 0.85

    if best_match:
        return {
            'detected': True,
            'source': best_match['platform'],
            'confidence': best_confidence,
            'position': best_match.get('corner', None),
            'detected_text': best_match['detected_text'],
            'detail': f"在图像{best_match.get('corner', '未知位置')}检测到「{best_match['platform']}」水印/签名",
            'all_matches': all_matches,
            'all_texts': [t['text'] for t in all_ocr_texts[:10]],
            'method': 'dalle2_color' if dalle2_result and best_match['keyword'] == 'color_squares' else 'ocr',
        }
    else:
        return {
            'detected': False,
            'source': None,
            'confidence': 0.0,
            'position': None,
            'detected_text': None,
            'detail': '未检测到已知 AI 平台水印',
            'all_matches': [],
            'all_texts': [t['text'] for t in all_ocr_texts[:10]],
            'method': 'ocr',
        }
